# Generated by Django 3.2.5 on 2021-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='stock_left',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Dispatched', 'Dispatched'), ('On The Way', 'On The Way'), ('Out for Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Order Cancelled', 'Order Cancelled')], default='Order Placed', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_condition',
            field=models.CharField(choices=[('IS', 'In-Stock'), ('OS', 'Out of Stock'), ('LS', 'Less Products')], max_length=3),
        ),
    ]
