# Generated by Django 3.2.5 on 2021-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210820_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='stock_left',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_left',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
