# Generated by Django 3.2.5 on 2021-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cutprice',
            field=models.FloatField(default=10),
        ),
    ]
