# Generated by Django 3.2.5 on 2021-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='status',
            new_name='rating',
        ),
    ]
