# Generated by Django 3.2.5 on 2021-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productreview_reviewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offers',
            field=models.CharField(default='efaefa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(choices=[('1-star', '1-star'), ('2-star', '2-star'), ('3-star', '3-star'), ('4-star', '4-star'), ('5-star', '5-star')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(max_length=200),
        ),
    ]
