# Generated by Django 3.2.5 on 2021-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210915_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offers',
            field=models.TextField(default='efaefa', max_length=1000),
        ),
    ]
