# Generated by Django 3.2.5 on 2021-09-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_product_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='Description about the Product here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_offers',
            field=models.TextField(default='Offers about the Product here', max_length=1000),
        ),
    ]
